version: '3.1'
services:
  db:
    image: mysql
    container_name: springboot
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3636:3636"
    volumes:
    - dev_data:/var/lib/mysql

volumes:
  dev_data: